Repository TeamCodeBreak/codeBreak-frontend, pull requests merged in 2021-12, with the labels that each got.

#88 adds conditional rendering to the reset button within break reminder …
  README.md
  src/components/break-modal/Modal.js
  src/components/break-reminder/BreakReminder.js
  src/img/danceGif.gif
Labels: enhancement

#94 adds new script for react with use on Apple M1 chips, works with Node…
  package.json
Labels: bug

#130 removes whitespace, converts multiline code blocks to single line for…
  src/components/food/Food.js
Labels: update

#135 changes ducks position to be fixed in browser screen, modifies animat…
  src/components/rubber-ducky/rubber-ducky.scss
Labels: update

#140 adds base-64 dependency to enable auth test to pass
  package-lock.json
  package.json
Labels: bug

#143 increases banner size and adds directions to rubber ducky
  src/components/home/home.scss
  src/components/rubber-ducky/RubberDucky.js
Labels: update

#146 fixes README typos
  README.md
Labels: update
